    
---
- name: "module_bigip_device_facts"
  hosts: tmos
  vars:
    bigip_device_facts: 
      server: "{{ ansible_host }}"
      gather_subset: "{{ bigip_device_facts_gather_subset | default(omit, True) }}"
      user: "{{ bigip_device_facts_user | default(omit, True) }}"
      server_port: "{{ bigip_device_facts_server_port | default(omit, True) }}"
      provider: "{{ bigip_device_facts_provider | default(omit, True) }}"
      password: "{{ bigip_device_facts_password | default(omit, True) }}"
      validate_certs: "{{ bigip_device_facts_validate_certs | default(omit, True) }}"
  tasks:
    - name: "bigip_device_facts"
      bigip_device_facts: "{{ bigip_device_facts }}"
      register: r_bigip_device_facts

    - name: "export r_bigip_device_facts"
      set_stats:
        data:
          r_bigip_device_facts: "{{ r_bigip_device_facts }}"