---
- name: "tmos.backup: fetch network configuration"
  bigip_command:
    server: "{{ ansible_host }}"
    commands: "show running-config"
  register: r_bigip_command

- name: "tmos.backup: create folder structure"
  file:
    path: "{{ r_tempfile.path }}/{{ inventory_hostname }}/config"
    state: directory

- name: "tmos.backup: copy configuration to repo folder"
  copy:
    content: "{{ r_bigip_command.stdout[0] }}"
    dest: "{{ r_tempfile.path }}/{{ inventory_hostname }}/config/running.cfg"
    force: "yes"
  notify: git_sync
